apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todolist
type: Opaque
stringData:
  DATABASE_HOST: "MTAuMC4xLjc="
  DATABASE_PORT: "5432"
  DATABASE_NAME: "todolist_prod"
  DATABASE_USER: "todolist"
  DATABASE_PASSWORD: "todolist123"